// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TruckerService.Data;

#nullable disable

namespace TruckerService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424144425_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("TruckerService.Models.Caminhao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ano")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Caminhoes");
                });

            modelBuilder.Entity("TruckerService.Models.Mecanico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mecanicos");
                });

            modelBuilder.Entity("TruckerService.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaminhaoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataHoraAbertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataHoraFechamento")
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DescricaoServicoRealizado")
                        .HasColumnType("TEXT");

                    b.Property<int?>("MecanicoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CaminhaoId");

                    b.HasIndex("MecanicoId");

                    b.ToTable("OrdensServico");
                });

            modelBuilder.Entity("TruckerService.Models.OrdemServico", b =>
                {
                    b.HasOne("TruckerService.Models.Caminhao", "Veiculo")
                        .WithMany()
                        .HasForeignKey("CaminhaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TruckerService.Models.Mecanico", "Mecanico")
                        .WithMany()
                        .HasForeignKey("MecanicoId");

                    b.Navigation("Mecanico");

                    b.Navigation("Veiculo");
                });
#pragma warning restore 612, 618
        }
    }
}
